language: swift
osx_image: xcode11.3
before_install:
- pod install
script: xcodebuild -workspace GiphyViewer.xcworkspace -scheme GiphyViewer -destination 'platform=iOS Simulator,name=iPhone 11 Pro' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
